# Generated by Django 4.2.23 on 2025-06-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('colour', models.CharField(blank=True, default='#A6C9EC', max_length=10, null=True)),
                ('colour_text', models.CharField(blank=True, default='#000000', max_length=10, null=True)),
            ],
        ),
    ]
