# Generated by Django 4.2.23 on 2025-06-14 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='selected_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.company'),
        ),
        migrations.AddField(
            model_name='person',
            name='selected_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.person'),
        ),
    ]
