# Generated by Django 4.2.23 on 2025-06-14 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_person_selected_company_person_selected_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.company'),
        ),
    ]
