# Generated by Django 4.2.23 on 2025-06-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answer_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='To_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('owner', models.CharField(blank=True, max_length=512, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('open', models.BooleanField(default=True)),
            ],
        ),
    ]
