# Generated by Django 4.2.23 on 2025-06-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_to_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('respondant', 'respondant')], default='Quarterly', max_length=10),
        ),
    ]
