# Generated by Django 4.2.23 on 2025-06-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_person_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Respondant', 'Respondant')], default='Respondant', max_length=10),
        ),
        migrations.AlterField(
            model_name='to_do',
            name='owner',
            field=models.CharField(blank=True, default='Darren', max_length=512, null=True),
        ),
    ]
