# Generated by Django 4.2.23 on 2025-06-15 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_answer_answered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='selected_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.period'),
        ),
        migrations.AddField(
            model_name='person',
            name='selected_status',
            field=models.TextField(blank=True, choices=[('Both', 'Both'), ('Answered', 'Answered'), ('Unanswered', 'Unanswered')], default=('Both', 'Both'), null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Respondent', 'Respondent')], default='Respondent', max_length=10),
        ),
    ]
