# Generated by Django 4.2.23 on 2025-06-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_person_selected_period_person_selected_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='selected_status',
            field=models.TextField(blank=True, choices=[('Answered', 'Answered'), ('Unanswered', 'Unanswered')], default=None, null=True),
        ),
    ]
