# Generated by Django 4.2.23 on 2025-06-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_person_selected_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_company_x', models.TextField(blank=True, null=True)),
                ('description_period', models.TextField(blank=True, null=True)),
                ('description_person', models.TextField(blank=True, null=True)),
                ('description_answer_type', models.TextField(blank=True, null=True)),
                ('description_question', models.TextField(blank=True, null=True)),
                ('description_answer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
