# Generated by Django 4.2.23 on 2025-06-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_descriptions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Descriptions',
        ),
    ]
