# Generated by Django 4.2.23 on 2025-06-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('colour', models.CharField(blank=True, default='#A6C9EC', max_length=10, null=True)),
                ('colour_text', models.CharField(blank=True, default='#000000', max_length=10, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('period', models.TextField(blank=True, null=True)),
                ('person', models.TextField(blank=True, null=True)),
                ('answer_type', models.TextField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
